version: '3.8'
services:
  app:
    image: amirmasoud/health:latest
    container_name: health_app
    restart: unless-stopped
    volumes:
      - ./.env:/var/www/.env
      - ./storage/:/var/www/storage/
      - ./public/:/var/www/public/
    networks:
      - health_app_network
  mariadb:
    image: mariadb:10.11.10
    container_name: health_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: health
      MARIADB_USER: root
      MARIADB_PASSWORD: secret
    volumes:
      - health_mariadb_data:/var/lib/mysql
    networks:
      - health_app_network
  nginx:
    image: nginx:latest
    container_name: health_nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - health_app_network
volumes:
  health_mariadb_data:
networks:
  health_app_network:
    driver: bridge
