version: '3.8'
services:
  app:
    image: amirmasoud/health:latest
    container_name: health_app
    restart: unless-stopped
    networks:
      - health_app_network
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
  mariadb:
    image: mariadb:10.11.10
    container_name: health_mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: health
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - health_app_network
  nginx:
    image: nginx:latest
    container_name: health_nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    networks:
      - health_app_network
volumes:
  mariadb_data:
networks:
  health_app_network:
    driver: bridge
